version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    #volumes:
    #  - ./cache.db:/app/cache.db
    environment:
      - RAPIDAPI_REVIEWS_KEY=
    restart: always
